apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    volume.kubernetes.io/selected-node: ip-127-0-0-1.us-west-2.compute.internal
  creationTimestamp: "2020-04-29T14:00:54Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mongodb
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    template: mongodb-persistent-template
  name: mongodb
  namespace: bookinfo
  resourceVersion: "404885541"
  selfLink: /api/v1/namespaces/bookinfo/persistentvolumeclaims/mongodb
  uid: d75f40a4-8a21-11ea-a5ee-02fdb1202f5a
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-d75f40a4-8a21-11ea-a5ee-02fdb1202f5a
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
