apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
  creationTimestamp: "2020-04-29T14:00:53Z"
  labels:
    app: mongodb
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    template: mongodb-persistent-template
  name: mongodb
  namespace: bookinfo
  resourceVersion: "404885065"
  selfLink: /api/v1/namespaces/bookinfo/services/mongodb
  uid: d73e3c91-8a21-11ea-a5ee-02fdb1202f5a
spec:
  clusterIP: 127.0.0.1
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
